services:
  mysql:
    image: mysql:8.0
    container_name: nabi_mysql
    restart: always
    env_file:
    - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - nabi-network

  adminer:
    image: adminer
    container_name: mi-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - nabi-network

volumes:
  mysql_data:

networks:
  nabi-network:
    external: true
